name: "ivabus"
description: ivabus's site/blog
url: https://ivabus.dev
lang: en
timezone: Europe/Moscow

permalink: "/:year/:month/:day/:title/"

collections:
  projects:
    output: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'LICENSE', 'shell.nix', 'gemset.nix']

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-minifier
  - rouge

markdown: kramdown

social:
  name: Ivan Bushchik
  links:
    - https://github.com/ivabus
    - https://vk.com/ivabus

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false
    wrap: true

jekyll-minifier:
  preserve_line_breaks: true
